/**
 * Phase 3.5B — the INTELLIGENCE SURFACE REGISTRY.
 *
 * One reviewed, machine-checkable answer to: for every intelligence surface the system builds or serves, who
 * builds it, what is served, what reads it, what route (if any) exposes it, what it is (predictive / descriptive
 * / shadow), who owns its freshness and lineage, how to regenerate it, and who consumes it.
 *
 * TYPES ONLY. The registry DATA lives in `docs/intelligence-surface-registry.json` (kept out of lib/ and app/ on purpose:
 * the repository's isolation tests text-scan those trees for module paths, and a registry necessarily names every
 * module). `test/intelligence-surface-registry.test.ts`
 * verifies every claim against the repository (artifacts exist, manifests carry the named version field,
 * readers/tests/docs exist, routes exist, declared consumers match the real import graph), so it cannot
 * silently drift the way prose inventories do. Phase 3.5C (Book-Ready) should extend THIS registry rather than
 * build a parallel one.
 *
 * Status is NEVER inferred from naming: `reachability` and `consumers` are checked against actual imports.
 */

/** Existing repository vocabulary; a surface may carry several. */
export type SurfaceStatus =
  | "ACTIVE" // serves production-facing decisions or is a live shared dependency
  | "SHADOW" // computed and exposed for observation; never influences a production recommendation
  | "DESCRIPTIVE_ONLY"
  | "RESEARCH_ONLY"
  | "DEPRECATED"
  | "UNREACHABLE"
  | "STALE"
  | "SOURCE_CONFLICT"
  | "UNSUPPORTED";

export type Reachability =
  | "FULLY_REACHABLE" // builder -> artifact -> loader -> route -> consumer
  | "EMBEDDED_IN_ROUTE" // no dedicated route; embedded in another route's response
  | "LIBRARY_ONLY_INTENTIONAL" // reader exists, no HTTP route by documented design
  | "INTERNAL_ARTIFACT" // audit/provenance artifact with no runtime reader, by design
  | "COMPUTED_AT_REQUEST"; // no served artifact; computed per request from canonical state

export type Reproducibility =
  | "PINNED_STATIC" // rebuilt only by deliberate command; a hash pin detects unrelated regeneration
  | "AUTO_REFRESHED" // regenerated by a scheduled workflow; checked structurally, not hash-pinned
  | "NO_ARTIFACT";

export interface IntelligenceSurface {
  id: string;
  name: string;
  owning_module: string;
  status: SurfaceStatus[];
  /** predictive/descriptive nature and deployment (from the manifest where one exists). */
  nature: string;
  deployment: string;
  builder: { command: string | null; entrypoints: string[] };
  served_artifacts: string[];
  manifest: string | null;
  /** manifest key that carries the surface version (checked to exist). */
  version_field: string | null;
  readers: string[];
  routes: string[];
  reachability: Reachability;
  source_data: string;
  data_cutoff_field: string | null;
  confidence_semantics: string;
  freshness_owner: string;
  lineage_owner: string;
  reproducibility: Reproducibility;
  docs: string[];
  tests: string[];
  /** lib/ modules (paths relative to lib/) that import this surface. Verified against the import graph. */
  consumers: string[];
  notes?: string;
}
