/**
 * PHASE 2 — R ↔ TypeScript parity for the calibrated RI-core projection.
 *
 * `analysis/phase2_calibration.R` ports `projectCoreForSeason` to R to sweep
 * shrinkage K and formula families over held-out seasons. This test asserts the
 * two implementations agree on a committed, position/age/sample-stratified
 * fixture set (`test/fixtures/phase2-parity.json`), regenerated by the harness.
 *
 * Documented tolerance: |R − TS| ≤ 1.0 PPR points per case, mean |Δ| ≤ 0.1.
 */

import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";

import { projectCoreForSeason } from "@/lib/projections/backtest";
import type { PlayerSeasonActual } from "@/lib/projections/actuals";
import type { FantasyPosition } from "@/lib/projections/schema";
import { PROJECTION_MODEL_VERSION } from "@/lib/projections/schema";

interface PriorSeasonFixture {
  season: number;
  position: FantasyPosition;
  gp: number;
  gs: number;
  off_snp: number;
  tm_off_snp: number;
  pass_att: number; pass_cmp: number; pass_yd: number; pass_td: number;
  pass_int: number; pass_rz_att: number;
  rush_att: number; rush_yd: number; rush_td: number; rush_rz_att: number; g2g_att: number;
  targets: number; rec: number; rec_yd: number; rec_td: number; rec_rz_tgt: number; rec_air_yd: number;
  fum_lost: number; pts_ppr: number;
}
interface ParityCase {
  player_id: string | number;
  target_season: number;
  position: FantasyPosition;
  age: number | null;
  r_predicted_points: number;
  prior_seasons: PriorSeasonFixture[];
}
interface ParityFixture {
  model_version: string;
  tolerance_abs: number;
  tolerance_mean_abs: number;
  cases: ParityCase[];
}

function toActual(pid: string, f: PriorSeasonFixture): PlayerSeasonActual {
  return {
    player_id: pid,
    season: f.season,
    position: f.position,
    team: null,
    gp: f.gp,
    gs: f.gs,
    off_snp: f.off_snp,
    tm_off_snp: f.tm_off_snp,
    snap_share: f.tm_off_snp > 0 ? f.off_snp / f.tm_off_snp : null,
    pass_att: f.pass_att,
    pass_cmp: f.pass_cmp,
    pass_yd: f.pass_yd,
    pass_td: f.pass_td,
    pass_int: f.pass_int,
    pass_rz_att: f.pass_rz_att,
    rush_att: f.rush_att,
    rush_yd: f.rush_yd,
    rush_td: f.rush_td,
    rush_rz_att: f.rush_rz_att,
    g2g_att: f.g2g_att,
    targets: f.targets,
    rec: f.rec,
    rec_yd: f.rec_yd,
    rec_td: f.rec_td,
    rec_air_yd: f.rec_air_yd,
    rec_rz_tgt: f.rec_rz_tgt,
    fum_lost: f.fum_lost,
    fgm: 0, fga: 0, fgm_yds: 0, xpm: 0, xpa: 0,
    def_sack: 0, def_int: 0, def_fum_rec: 0, def_td: 0, def_safety: 0,
    pts_ppr: f.pts_ppr,
  };
}

const fixture = JSON.parse(
  readFileSync(join(process.cwd(), "test", "fixtures", "phase2-parity.json"), "utf8"),
) as ParityFixture;

describe("R ↔ TS parity — calibrated RI-core (ri-structural-2026.2)", () => {
  it("fixture is for the current model version", () => {
    assert.equal(fixture.model_version, PROJECTION_MODEL_VERSION);
    assert.ok(fixture.cases.length >= 20, `only ${fixture.cases.length} parity cases`);
  });

  it("every case agrees within the documented per-case tolerance", () => {
    const diffs: number[] = [];
    for (const c of fixture.cases) {
      const pid = String(c.player_id);
      const prior = c.prior_seasons.map((s) => toActual(pid, s));
      const ts = projectCoreForSeason(pid, c.position, c.age, prior, c.target_season);
      assert.ok(ts, `TS produced no projection for ${pid} ${c.target_season}`);
      const d = Math.abs(ts.predicted_points - c.r_predicted_points);
      diffs.push(d);
      assert.ok(
        d <= fixture.tolerance_abs,
        `${c.position} ${pid} ${c.target_season}: R ${c.r_predicted_points} vs TS ${ts.predicted_points} (Δ ${d.toFixed(3)} > ${fixture.tolerance_abs})`,
      );
    }
    const meanAbs = diffs.reduce((a, b) => a + b, 0) / diffs.length;
    assert.ok(
      meanAbs <= fixture.tolerance_mean_abs,
      `mean |R − TS| ${meanAbs.toFixed(4)} > ${fixture.tolerance_mean_abs}`,
    );
  });

  it("covers every skill position and a spread of ages", () => {
    const positions = new Set(fixture.cases.map((c) => c.position));
    for (const p of ["QB", "RB", "WR", "TE"]) {
      assert.ok(positions.has(p as FantasyPosition), `no parity case for ${p}`);
    }
    const ages = fixture.cases.map((c) => c.age).filter((a): a is number => a != null);
    assert.ok(Math.max(...ages) - Math.min(...ages) >= 8, "age spread too narrow");
  });
});
