/** GENERATED by analysis/phase3_rookie_role_model.R -- do not edit by hand.
 *  sleeper_id -> 2026 NFL draft round / overall pick for skill rookies.
 *  Source: nflverse load_draft_picks(2026) x nflreadr load_ff_playerids(). */
export interface RookieDraftRow {
  sleeper_id: string; gsis_id?: string; name: string;
  position: string; round: number; pick: number;
}
export const ROOKIE_DRAFT_2026: { model_version: string; generated_at: string; picks: RookieDraftRow[] } = {
  "model_version": "ri-structural-2026.3",
  "generated_at": "2026-09-01T05:43:03Z",
  "picks": [
    {
      "sleeper_id": "13269",
      "gsis_id": "MEN516487",
      "name": "Fernando Mendoza",
      "position": "QB",
      "round": 1,
      "pick": 1
    },
    {
      "sleeper_id": "13287",
      "gsis_id": "LOV121782",
      "name": "Jeremiyah Love",
      "position": "RB",
      "round": 1,
      "pick": 3
    },
    {
      "sleeper_id": "13279",
      "gsis_id": "TAT143045",
      "name": "Carnell Tate",
      "position": "WR",
      "round": 1,
      "pick": 4
    },
    {
      "sleeper_id": "13281",
      "gsis_id": "TYS405541",
      "name": "Jordyn Tyson",
      "position": "WR",
      "round": 1,
      "pick": 8
    },
    {
      "sleeper_id": "13275",
      "gsis_id": "SIM639376",
      "name": "Ty Simpson",
      "position": "QB",
      "round": 1,
      "pick": 13
    },
    {
      "sleeper_id": "13330",
      "gsis_id": "SAD482340",
      "name": "Kenyon Sadiq",
      "position": "TE",
      "round": 1,
      "pick": 16
    },
    {
      "sleeper_id": "13294",
      "gsis_id": "LEM694125",
      "name": "Makai Lemon",
      "position": "WR",
      "round": 1,
      "pick": 20
    },
    {
      "sleeper_id": "13298",
      "gsis_id": "CON046719",
      "name": "KC Concepcion",
      "position": "WR",
      "round": 1,
      "pick": 24
    },
    {
      "sleeper_id": "13276",
      "gsis_id": "COO816508",
      "name": "Omar Cooper Jr.",
      "position": "WR",
      "round": 1,
      "pick": 30
    },
    {
      "sleeper_id": "13286",
      "gsis_id": "PRI206342",
      "name": "Jadarian Price",
      "position": "RB",
      "round": 1,
      "pick": 32
    },
    {
      "sleeper_id": "13417",
      "name": "De'Zhaun Stribling",
      "position": "WR",
      "round": 2,
      "pick": 33
    },
    {
      "sleeper_id": "13346",
      "gsis_id": "BOS677861",
      "name": "Denzel Boston",
      "position": "WR",
      "round": 2,
      "pick": 39
    },
    {
      "sleeper_id": "13274",
      "gsis_id": "BER218265",
      "name": "Germie Bernard",
      "position": "WR",
      "round": 2,
      "pick": 47
    },
    {
      "sleeper_id": "13349",
      "gsis_id": "STO806346",
      "name": "Eli Stowers",
      "position": "TE",
      "round": 2,
      "pick": 54
    },
    {
      "sleeper_id": "13299",
      "gsis_id": "BOE586077",
      "name": "Nate Boerkircher",
      "position": "TE",
      "round": 2,
      "pick": 56
    },
    {
      "sleeper_id": "13307",
      "gsis_id": "KLE258860",
      "name": "Marlin Klein",
      "position": "TE",
      "round": 2,
      "pick": 59
    },
    {
      "sleeper_id": "13278",
      "gsis_id": "KLA269938",
      "name": "Max Klare",
      "position": "TE",
      "round": 2,
      "pick": 61
    },
    {
      "sleeper_id": "13322",
      "gsis_id": "ROU550040",
      "name": "Sam Roush",
      "position": "TE",
      "round": 3,
      "pick": 69
    },
    {
      "sleeper_id": "13301",
      "gsis_id": "WIL143106",
      "name": "Antonio Williams",
      "position": "WR",
      "round": 3,
      "pick": 71
    },
    {
      "sleeper_id": "13319",
      "name": "Oscar Delp",
      "position": "TE",
      "round": 3,
      "pick": 73
    },
    {
      "sleeper_id": "13285",
      "gsis_id": "FIE775129",
      "name": "Malachi Fields",
      "position": "WR",
      "round": 3,
      "pick": 74
    },
    {
      "sleeper_id": "13296",
      "gsis_id": "DOU210628",
      "name": "Caleb Douglas",
      "position": "WR",
      "round": 3,
      "pick": 75
    },
    {
      "sleeper_id": "13289",
      "gsis_id": "ALL015451",
      "name": "Drew Allar",
      "position": "QB",
      "round": 3,
      "pick": 76
    },
    {
      "sleeper_id": "13320",
      "gsis_id": "BRA531428",
      "name": "Zachariah Branch",
      "position": "WR",
      "round": 3,
      "pick": 79
    },
    {
      "sleeper_id": "13293",
      "gsis_id": "LAN311008",
      "name": "Ja'Kobi Lane",
      "position": "WR",
      "round": 3,
      "pick": 80
    },
    {
      "sleeper_id": "13353",
      "gsis_id": "BRA836631",
      "name": "Chris Brazzell II",
      "position": "WR",
      "round": 3,
      "pick": 83
    },
    {
      "sleeper_id": "13317",
      "gsis_id": "HUR541377",
      "name": "Ted Hurst",
      "position": "WR",
      "round": 3,
      "pick": 84
    },
    {
      "sleeper_id": "13434",
      "gsis_id": "KAC282861",
      "name": "Will Kacmarek",
      "position": "TE",
      "round": 3,
      "pick": 87
    },
    {
      "sleeper_id": "13411",
      "gsis_id": "THO417520",
      "name": "Zavion Thomas",
      "position": "WR",
      "round": 3,
      "pick": 89
    },
    {
      "sleeper_id": "13414",
      "gsis_id": "BLA097235",
      "name": "Kaelon Black",
      "position": "RB",
      "round": 3,
      "pick": 90
    },
    {
      "sleeper_id": "13311",
      "gsis_id": "BEL267684",
      "name": "Chris Bell",
      "position": "WR",
      "round": 3,
      "pick": 94
    },
    {
      "sleeper_id": "13421",
      "gsis_id": "RAR148318",
      "name": "Eli Raridon",
      "position": "TE",
      "round": 3,
      "pick": 95
    },
    {
      "sleeper_id": "13380",
      "gsis_id": "THO495568",
      "name": "Brenen Thompson",
      "position": "WR",
      "round": 4,
      "pick": 105
    },
    {
      "sleeper_id": "13345",
      "gsis_id": "COL293648",
      "name": "Jonah Coleman",
      "position": "RB",
      "round": 4,
      "pick": 108
    },
    {
      "sleeper_id": "13303",
      "gsis_id": "KLU066027",
      "name": "Cade Klubnik",
      "position": "QB",
      "round": 4,
      "pick": 110
    },
    {
      "sleeper_id": "13268",
      "gsis_id": "SAR527100",
      "name": "Elijah Sarratt",
      "position": "WR",
      "round": 4,
      "pick": 115
    },
    {
      "sleeper_id": "13491",
      "gsis_id": "WET055619",
      "name": "Kaden Wetjen",
      "position": "WR",
      "round": 4,
      "pick": 121
    },
    {
      "sleeper_id": "13305",
      "gsis_id": "WAS797326",
      "name": "Mike Washington Jr.",
      "position": "RB",
      "round": 4,
      "pick": 122
    },
    {
      "sleeper_id": "13402",
      "gsis_id": "BEL597603",
      "name": "Skyler Bell",
      "position": "WR",
      "round": 4,
      "pick": 125
    },
    {
      "sleeper_id": "13420",
      "gsis_id": "LAN016345",
      "name": "Bryce Lance",
      "position": "WR",
      "round": 4,
      "pick": 136
    },
    {
      "sleeper_id": "13477",
      "name": "Colbie Young",
      "position": "WR",
      "round": 4,
      "pick": 140
    },
    {
      "sleeper_id": "13297",
      "gsis_id": "VIR271235",
      "name": "Reggie Virgil",
      "position": "WR",
      "round": 5,
      "pick": 143
    },
    {
      "sleeper_id": "13400",
      "gsis_id": "JOL735174",
      "name": "Justin Joly",
      "position": "TE",
      "round": 5,
      "pick": 152
    },
    {
      "sleeper_id": "13516",
      "gsis_id": "BRE060106",
      "name": "Max Bredeson",
      "position": "TE",
      "round": 5,
      "pick": 159
    },
    {
      "sleeper_id": "13337",
      "gsis_id": "JOH224817",
      "name": "Emmett Johnson",
      "position": "RB",
      "round": 5,
      "pick": 161
    },
    {
      "sleeper_id": "13408",
      "gsis_id": "KOZ404039",
      "name": "Tanner Koziol",
      "position": "TE",
      "round": 5,
      "pick": 164
    },
    {
      "sleeper_id": "13412",
      "gsis_id": "LAW090280",
      "name": "Kendrick Law",
      "position": "WR",
      "round": 5,
      "pick": 168
    },
    {
      "sleeper_id": "13433",
      "gsis_id": "NOW373761",
      "name": "Riley Nowakowski",
      "position": "TE",
      "round": 5,
      "pick": 169
    },
    {
      "sleeper_id": "13435",
      "name": "Joe Royer",
      "position": "TE",
      "round": 5,
      "pick": 170
    },
    {
      "sleeper_id": "13273",
      "gsis_id": "CUE040912",
      "name": "Josh Cuevas",
      "position": "TE",
      "round": 5,
      "pick": 173
    },
    {
      "sleeper_id": "13302",
      "gsis_id": "RAN022436",
      "name": "Adam Randall",
      "position": "RB",
      "round": 5,
      "pick": 174
    },
    {
      "sleeper_id": "13413",
      "gsis_id": "ALL092954",
      "name": "Cyrus Allen",
      "position": "WR",
      "round": 5,
      "pick": 176
    },
    {
      "sleeper_id": "13338",
      "gsis_id": "COL362413",
      "name": "Kevin Coleman Jr.",
      "position": "WR",
      "round": 5,
      "pick": 177
    },
    {
      "sleeper_id": "13335",
      "gsis_id": "PAY546690",
      "name": "Cole Payton",
      "position": "QB",
      "round": 5,
      "pick": 178
    },
    {
      "sleeper_id": "13429",
      "gsis_id": "TRA291459",
      "name": "Seydou Traore",
      "position": "TE",
      "round": 5,
      "pick": 180
    },
    {
      "sleeper_id": "13306",
      "gsis_id": "GRE361852",
      "name": "Taylen Green",
      "position": "QB",
      "round": 6,
      "pick": 182
    },
    {
      "sleeper_id": "13308",
      "gsis_id": "SHA375359",
      "name": "Bauer Sharp",
      "position": "TE",
      "round": 6,
      "pick": 185
    },
    {
      "sleeper_id": "13405",
      "gsis_id": "ALL532376",
      "name": "Kaytron Allen",
      "position": "RB",
      "round": 6,
      "pick": 187
    },
    {
      "sleeper_id": "13533",
      "gsis_id": "BRO268113",
      "name": "Barion Brown",
      "position": "WR",
      "round": 6,
      "pick": 190
    },
    {
      "sleeper_id": "13394",
      "gsis_id": "CAM108646",
      "name": "Josh Cameron",
      "position": "WR",
      "round": 6,
      "pick": 191
    },
    {
      "sleeper_id": "13329",
      "gsis_id": "BEN601117",
      "name": "Malik Benson",
      "position": "WR",
      "round": 6,
      "pick": 195
    },
    {
      "sleeper_id": "13347",
      "gsis_id": "CLA041524",
      "name": "Demond Claiborne",
      "position": "RB",
      "round": 6,
      "pick": 198
    },
    {
      "sleeper_id": "13313",
      "gsis_id": "HEN199637",
      "name": "Emmanuel Henderson Jr.",
      "position": "WR",
      "round": 6,
      "pick": 199
    },
    {
      "sleeper_id": "13554",
      "gsis_id": "WIL189259",
      "name": "CJ Williams",
      "position": "WR",
      "round": 6,
      "pick": 203
    },
    {
      "sleeper_id": "13541",
      "gsis_id": "BON235618",
      "name": "Lewis Bond",
      "position": "WR",
      "round": 6,
      "pick": 204
    },
    {
      "sleeper_id": "13582",
      "gsis_id": "SMI038569",
      "name": "Anthony Smith",
      "position": "WR",
      "round": 7,
      "pick": 218
    },
    {
      "sleeper_id": "13282",
      "gsis_id": "END438361",
      "name": "Jack Endries",
      "position": "TE",
      "round": 7,
      "pick": 221
    },
    {
      "sleeper_id": "13557",
      "gsis_id": "KAL252591",
      "name": "Athan Kaliakmanis",
      "position": "QB",
      "round": 7,
      "pick": 223
    },
    {
      "sleeper_id": "13422",
      "gsis_id": "KAN023071",
      "name": "Jaren Kanak",
      "position": "TE",
      "round": 7,
      "pick": 225
    },
    {
      "sleeper_id": "13295",
      "gsis_id": "MOR767384",
      "name": "Behren Morton",
      "position": "QB",
      "round": 7,
      "pick": 234
    },
    {
      "sleeper_id": "13424",
      "gsis_id": "MCG547540",
      "name": "Seth McGowan",
      "position": "RB",
      "round": 7,
      "pick": 237
    },
    {
      "sleeper_id": "13403",
      "gsis_id": "MIL303300",
      "name": "Jam Miller",
      "position": "RB",
      "round": 7,
      "pick": 245
    },
    {
      "sleeper_id": "13580",
      "gsis_id": "RYA022232",
      "name": "Carsen Ryan",
      "position": "TE",
      "round": 7,
      "pick": 248
    },
    {
      "sleeper_id": "13404",
      "gsis_id": "NUS440041",
      "name": "Garrett Nussmeier",
      "position": "QB",
      "round": 7,
      "pick": 249
    },
    {
      "sleeper_id": "13333",
      "name": "Deion Burks",
      "position": "WR",
      "round": 7,
      "pick": 254
    },
    {
      "sleeper_id": "13577",
      "gsis_id": "BEN687044",
      "name": "Dallen Bentley",
      "position": "TE",
      "round": 7,
      "pick": 256
    }
  ]
};
