/** Phase 5 — machine-readable FEATURE-FAMILY registry (spec §27, §31). Every family classified BEFORE use. Unsafe families never enter a fitted claim. */
import type { Availability, EvidenceOrigin, HistoryClass, PredictiveClass, Position } from "./contract";

export interface FeatureFamily {
  id: string; title: string; positions: Array<Position | "TEAM">; source: string; origin: EvidenceOrigin; availability: Availability;
  /** can this family be reconstructed AS OF a past week for an honest backtest? */
  history_class: HistoryClass; predictive_class: PredictiveClass;
  /** may it ever enter a FITTED claim? false for retrospective/unsafe/descriptive. */
  fit_eligible: boolean;
  first_supported_season: number | null; note: string;
}
const F = (f: FeatureFamily): FeatureFamily => f;

export const FEATURE_FAMILIES: FeatureFamily[] = [
  F({ id: "coverage.man_zone", title: "Man vs zone interaction", positions: ["QB", "WR", "TE", "RB"], source: "nflverse participation (charted man/zone)", origin: "OBSERVED_DEFENSIVE_TENDENCY", availability: "PRIOR_ONLY", history_class: "RECONSTRUCTABLE_AS_OF", predictive_class: "PREDICTIVE_CANDIDATE_UNVALIDATED", fit_eligible: true, first_supported_season: 2018, note: "Tier D qb_coverage: EXPLANATORY_ONLY (no gain over production-like baseline). Receiver version untested before Phase 5 evaluation." }),
  F({ id: "coverage.shell", title: "Coverage family/shell mix", positions: ["TEAM"], source: "nflverse participation (defense_coverage_type)", origin: "OBSERVED_DEFENSIVE_TENDENCY", availability: "PRIOR_ONLY", history_class: "RECONSTRUCTABLE_AS_OF", predictive_class: "DESCRIPTIVE_CONTEXT", fit_eligible: false, first_supported_season: 2018, note: "Source-native buckets (Cover 0/1/2/3/4/6, 2-man) preserved; no per-player shell interaction exists (receiver data is man/zone only)." }),
  F({ id: "area.pass_depth_third", title: "Target-area interaction (depth × field third)", positions: ["QB", "WR", "TE", "RB"], source: "nflverse play-by-play", origin: "OBSERVED_PLAYER_PROFILE", availability: "PRIOR_ONLY", history_class: "TRUE_AS_OF", predictive_class: "PREDICTIVE_CANDIDATE_UNVALIDATED", fit_eligible: true, first_supported_season: 2012, note: "Target LOCATION, not receiver alignment. Tier D wr_spatial EXPLANATORY_ONLY, te_spatial REJECTED, qb_spatial EXPLANATORY_ONLY." }),
  F({ id: "route.family", title: "Targeted-route family", positions: ["WR", "TE", "RB"], source: "nflverse participation (route)", origin: "OBSERVED_PLAYER_PROFILE", availability: "PRIOR_ONLY", history_class: "RECONSTRUCTABLE_AS_OF", predictive_class: "DESCRIPTIVE_CONTEXT", fit_eligible: false, first_supported_season: 2018, note: "TARGETED routes only (share of targets, not routes run). No defense-side route-family allowed data exists, so no interaction is computed — player side only." }),
  F({ id: "explosive.area", title: "Explosive-play environment by depth", positions: ["QB", "WR", "TE", "RB"], source: "nflverse play-by-play", origin: "OBSERVED_DEFENSIVE_TENDENCY", availability: "PRIOR_ONLY", history_class: "TRUE_AS_OF", predictive_class: "PREDICTIVE_CANDIDATE_UNVALIDATED", fit_eligible: true, first_supported_season: 2012, note: "Explosive = pass gain >= 16 / rush >= 12 yards (Phase 9 config)." }),
  F({ id: "pressure.qb_response", title: "Pressure × QB response", positions: ["QB"], source: "nflverse participation (was_pressure)", origin: "OBSERVED_DEFENSIVE_TENDENCY", availability: "PRIOR_ONLY", history_class: "RECONSTRUCTABLE_AS_OF", predictive_class: "PREDICTIVE_CANDIDATE_UNVALIDATED", fit_eligible: true, first_supported_season: 2016, note: "Tier D qb_pressure EXPLANATORY_ONLY. Pressure rate reflects the opposing QB as well as the defense — causality not claimed." }),
  F({ id: "pressure.rusher_count", title: "Rusher-count response", positions: ["QB"], source: "nflverse participation (number_of_pass_rushers)", origin: "OBSERVED_PLAYER_PROFILE", availability: "PRIOR_ONLY", history_class: "RECONSTRUCTABLE_AS_OF", predictive_class: "DESCRIPTIVE_CONTEXT", fit_eligible: false, first_supported_season: 2016, note: "Blitz proxy = 5+ rushers. Defense-side rusher count is a proxy, not a charted blitz." }),
  F({ id: "run.direction", title: "Run direction (left/middle/right)", positions: ["RB"], source: "nflverse play-by-play (run_location)", origin: "OBSERVED_PLAYER_PROFILE", availability: "PRIOR_ONLY", history_class: "TRUE_AS_OF", predictive_class: "PREDICTIVE_CANDIDATE_UNVALIDATED", fit_eligible: true, first_supported_season: 2012, note: "Tier D rb_direction EXPLANATORY_ONLY. Left/middle/right — NOT inside/outside (no such label exists in the source)." }),
  F({ id: "run.gap", title: "Run gap (end/tackle/guard)", positions: ["RB"], source: "nflverse play-by-play (run_gap)", origin: "OBSERVED_PLAYER_PROFILE", availability: "PRIOR_ONLY", history_class: "TRUE_AS_OF", predictive_class: "PREDICTIVE_CANDIDATE_UNVALIDATED", fit_eligible: true, first_supported_season: 2012, note: "Source gap granularity is END/TACKLE/GUARD only; no zone/gap/power/counter scheme label exists." }),
  F({ id: "run.box", title: "Box environment", positions: ["RB"], source: "nflverse participation (defenders_in_box)", origin: "OBSERVED_DEFENSIVE_TENDENCY", availability: "PRIOR_ONLY", history_class: "RECONSTRUCTABLE_AS_OF", predictive_class: "PREDICTIVE_CANDIDATE_UNVALIDATED", fit_eligible: true, first_supported_season: 2016, note: "Tier D rb_box REJECTED. Box count is the only front evidence; front ALIGNMENT is unsupported." }),
  F({ id: "rb.receiving_vs_coverage", title: "RB/TE receiving vs unit coverage", positions: ["RB", "TE"], source: "Football Intelligence coverage_allowed_epa_<POS>", origin: "OBSERVED_DEFENSIVE_TENDENCY", availability: "LIVE_CURRENT", history_class: "RECONSTRUCTABLE_AS_OF", predictive_class: "DESCRIPTIVE_CONTEXT", fit_eligible: false, first_supported_season: 2019, note: "UNIT-level (all LB/S/CB coverage allowed to the position group); never an individual defender." }),
  F({ id: "scoring.red_zone", title: "Scoring-opportunity interaction", positions: ["QB", "RB", "WR", "TE"], source: "Role rz shares + FI def_rz_td_rate_allowed", origin: "DESCRIPTIVE_CONTEXT", availability: "LIVE_CURRENT", history_class: "RECONSTRUCTABLE_AS_OF", predictive_class: "DESCRIPTIVE_CONTEXT", fit_eligible: false, first_supported_season: 2019, note: "Red-zone role and defense red-zone efficiency shown side by side; no touchdown expectation is derived from last week's touchdowns." }),
  F({ id: "team.pass_vs_pass_defense", title: "Team pass game vs pass defense", positions: ["TEAM"], source: "Football Intelligence contextual_matchup_feature", origin: "DESCRIPTIVE_CONTEXT", availability: "LIVE_CURRENT", history_class: "RECONSTRUCTABLE_AS_OF", predictive_class: "DESCRIPTIVE_CONTEXT", fit_eligible: false, first_supported_season: 2019, note: "Predictive status routed per component by FI (off:X|def:Y); consumed, never re-derived." }),
  F({ id: "history.player_vs_defense", title: "Player historical results vs this defense/coach", positions: ["QB", "RB", "WR", "TE"], source: "none as-of", origin: "UNSUPPORTED", availability: "UNAVAILABLE", history_class: "UNSAFE_FOR_BACKTEST", predictive_class: "UNSUPPORTED", fit_eligible: false, first_supported_season: null, note: "No chronology-safe per-game role/scheme-at-the-time store exists; whole-career aggregates would leak later seasons into earlier games." }),
  F({ id: "assignment.cornerback", title: "Cornerback assignment / shadow coverage", positions: ["WR", "TE"], source: "none", origin: "UNSUPPORTED", availability: "UNAVAILABLE", history_class: "UNSAFE_FOR_BACKTEST", predictive_class: "UNSUPPORTED", fit_eligible: false, first_supported_season: null, note: "No assignment data; depth charts do not establish who covers whom." }),
  F({ id: "alignment.slot_boundary", title: "Receiver alignment (slot/perimeter/inline)", positions: ["WR", "TE", "RB"], source: "none", origin: "UNSUPPORTED", availability: "UNAVAILABLE", history_class: "UNSAFE_FOR_BACKTEST", predictive_class: "UNSUPPORTED", fit_eligible: false, first_supported_season: null, note: "Target location is not alignment; no alignment source exists in the repository." }),
];
export const familyById = (id: string): FeatureFamily | undefined => FEATURE_FAMILIES.find((f) => f.id === id);
