/** Phase 5 — what the system genuinely does NOT know. Never inferred, never filled with a proxy; every item names the chapters that stay UNSUPPORTED. */
import type { Position, UnsupportedItem } from "./contract";

const U = (id: string, asked: string, reason: string, would_need: string, chapter_ids: string[]): UnsupportedItem => ({ id, asked, reason, would_need, chapter_ids });
export const UNSUPPORTED: UnsupportedItem[] = [
  U("cornerback_assignment", "Which defender is expected to cover him (shadow, side-based, slot CB, travel, injury replacement)?", "No assignment/tracking data exists in any source; a depth chart does not establish who covers whom, and no coverage-responsibility field is published.", "player-tracking or charted matchup-assignment data with chronology-safe history", ["matchup.cornerback_assignment"]),
  U("receiver_alignment", "Does he line up in the slot, on the perimeter, inline or in the backfield — and how does the defense defend those areas?", "Target location (depth × field third) is not alignment; no alignment source exists in the repository (participation has no per-player alignment column).", "charted or tracked receiver alignment per snap", ["defense.slot_boundary", "why.alignment"]),
  U("defense_front_alignment", "What front does the defense show (4-3, 3-4, odd/even, over/under)?", "Only box COUNT (defenders in box) and heavy-box rate exist; front alignment is not published.", "charted defensive front alignment", ["defense.front", "game.fronts"]),
  U("personnel_groupings", "How do offensive personnel (11/12/21) meet defensive personnel (base/nickel/dime)?", "No personnel-grouping data is served on either side; offensive formation buckets (shotgun, under center, …) exist for QBs but are not personnel.", "participation personnel columns with defensive personnel response", ["defense.personnel"]),
  U("run_fit_scheme", "Is the run defense strong against zone vs gap/power/counter, short-yardage or goal-line runs?", "The source labels runs only by direction (left/middle/right) and gap (end/tackle/guard); zone/gap/power/counter, short-yardage and goal-line splits are not published.", "charted run-scheme and situation splits", ["defense.run_fits"]),
  U("linebacker_safety_coverage_individual", "Can this linebacker/safety cover the areas he uses?", "Only UNIT-level coverage allowed to a position group exists (Football Intelligence); no defender-level coverage.", "defender-level coverage tracking", []),
  U("game_script_probabilities", "How likely is he to be leading, trailing or in clock-control mode, and how does his usage change?", "No reliable game-script probabilities or per-script usage splits are served (no spreads/totals feed). Scenario sensitivity is exposed instead of false precision.", "betting-line/win-probability feed and script-split usage", ["team.game_script", "why.game_script"]),
  U("coach_history", "How has he performed against this defensive coordinator/head coach historically?", "Coordinator identity by week is not served (only a per-season coordinator_known flag and a scheme-reset hint), and per-game role/scheme-at-the-time data is not stored, so any historical head-to-head would leak later seasons.", "chronology-safe per-game coordinator and role snapshots", []),
  U("offensive_line_player_level", "Can this specific offensive line block this specific rush?", "Only team-level pressure/sack rates allowed exist; no player-level pass-block or run-block evidence.", "player-level line grades with chronology-safe history", ["game.line_play"]),
  U("route_family_allowed", "Does the defense allow more of a specific route family (slants, crossers, go routes)?", "Route data exists for the PLAYER side only (targeted routes); no defense-side route-allowed table exists, so the route interaction is not computed.", "defense-side allowed-by-route-family table", []),
  U("current_season_charting", "What did this defense/player actually do in 2026 games (man/zone, pressure, box)?", "Participation-derived families are PRIOR_ONLY for 2026 (data through 2025 w18); no 2026 observation is available yet.", "2026 participation/FTN publication", []),
];
export function unsupportedFor(_position: Position | "TEAM"): UnsupportedItem[] { void _position; return UNSUPPORTED; }
