# ===========================================================================
# Injury -> Opportunity Propagation Intelligence -- Checkpoint D.
# Permanent NSE regression test (spec §24/§50), R side. Re-verifies the
# committed fixture (analysis/opportunity_propagation/tests/fixtures/
# r_ts_parity_fixture.json, generated by generate_parity_fixtures.R)
# against the REAL, live `inheritance_rate_lookup()` /
# `allocate_candidate4_hierarchical()` functions -- not a grep for the bug
# pattern, an actual re-run of the served lookup/allocation path. Both
# Checkpoints B and C found bugs where a function parameter named
# identically to a data.table column caused a self-reference (always-TRUE
# comparison) instead of a scalar lookup, silently collapsing every rate to
# the 0.5 default. This test's fixture has two groups (team AAA vs BBB,
# same dimension/position) with known, DIFFERENT historical rates, neither
# equal to 0.5 -- that bug class cannot reappear here without a visible
# failure.
# ===========================================================================
library(testthat)
suppressMessages({ library(dplyr); library(data.table); library(jsonlite) })

BASE <- file.path(Sys.getenv("FI_ROOT", getwd()), "analysis", "opportunity_propagation")
source(file.path(BASE, "config.R"))
source(file.path(BASE, "lib_fast_baselines.R"))
source(file.path(BASE, "lib_redistribution_observed.R"))
source(file.path(BASE, "lib_propagation_model.R"))

fixture <- jsonlite::fromJSON(file.path(BASE, "tests", "fixtures", "r_ts_parity_fixture.json"), simplifyVector = FALSE)

rebuild_priors <- function(fixture) {
  to_dt <- function(rows) rbindlist(lapply(rows, as.data.table))
  list(league = to_dt(fixture$priors$league), position = to_dt(fixture$priors$position), team = to_dt(fixture$priors$team))
}
priors <- rebuild_priors(fixture)
position_weights <- rbindlist(lapply(fixture$position_weights, as.data.table))

test_that("NSE regression: team AAA/WR and BBB/WR target_share rates are distinct, neither is 0.5", {
  rate_aaa <- inheritance_rate_lookup(priors, "target_share", "AAA", "WR")
  rate_bbb <- inheritance_rate_lookup(priors, "target_share", "BBB", "WR")
  expect_false(rate_aaa == rate_bbb)
  expect_false(rate_aaa == 0.5)
  expect_false(rate_bbb == 0.5)
  expect_equal(rate_aaa, fixture$nse_regression_case$rate_team_AAA_WR_target_share)
  expect_equal(rate_bbb, fixture$nse_regression_case$rate_team_BBB_WR_target_share)
})

test_that("NSE regression: attach_inheritance_rate (the REAL vectorized path the model uses) agrees with the scalar lookup", {
  bv <- data.table(dimension = c("target_share", "target_share"), team = c("AAA", "BBB"), absent_position = c("WR", "WR"))
  out <- attach_inheritance_rate(copy(bv), priors)
  expect_equal(out$rate[out$team == "AAA"], fixture$nse_regression_case$rate_team_AAA_WR_target_share)
  expect_equal(out$rate[out$team == "BBB"], fixture$nse_regression_case$rate_team_BBB_WR_target_share)
})

test_that("NSE regression: unseen team/position/dimension fall through the hierarchy visibly, never silently team-specific", {
  expect_equal(inheritance_rate_lookup(priors, "target_share", "ZZZ_UNSEEN", "WR"), fixture$nse_regression_case$rate_unseen_team_falls_to_position_prior)
  expect_equal(inheritance_rate_lookup(priors, "rush_share", "ZZZ_UNSEEN", "QB"), fixture$nse_regression_case$rate_unseen_position_falls_to_league_prior)
  expect_equal(inheritance_rate_lookup(priors, "no_such_dimension", "AAA", "WR"), 0.5)
})

test_that("full allocator (allocate_candidate4_hierarchical) reproduces the fixture's own recorded expected_predictions exactly", {
  for (scenario in fixture$scenarios) {
    events_meta <- data.table(absence_event_id = "fixture_event", team = scenario$team, position = scenario$absent_position)
    domain_accounting_val <- data.table(absence_event_id = "fixture_event", domain = "FIXTURE", dimension = scenario$dimension, vacated_opportunity = scenario$vacated_opportunity)
    beneficiary_val <- rbindlist(lapply(scenario$candidates, function(c) {
      data.table(absence_event_id = "fixture_event", domain = "FIXTURE", dimension = scenario$dimension,
                beneficiary_gsis_id = c$id, beneficiary_position = c$position,
                pre_event_recent = c$pre_event_recent, pre_event_season = c$pre_event_season)
    }))
    pred <- allocate_candidate4_hierarchical(beneficiary_val, domain_accounting_val, events_meta, priors, position_weights)
    for (expected in scenario$expected_predictions) {
      actual <- pred[beneficiary_gsis_id == expected$gsis_id]
      expect_equal(nrow(actual), 1, label = paste(scenario$name, expected$gsis_id))
      expect_equal(actual$pre_event_role, expected$pre_event_role, tolerance = 1e-9, label = paste(scenario$name, expected$gsis_id, "pre_event_role"))
    }
  }
})
