/** Phase 5 Checkpoint H — READ-ONLY live certification on real players and real defenses. No writes, no lineup/transaction action. */
import { fileMatchupSource } from "@/lib/matchup2/source-files";
import { buildMatchupContext } from "@/lib/matchup2/context";
import { evaluatePlayer } from "@/lib/matchup2/engine";
import { loadPlayerDirectory } from "@/lib/analysis-book/directory";
import { getEvidence } from "@/lib/book-ready/query";
import type { MatchupEvaluation } from "@/lib/matchup2/contract";

(async () => {
  const src = fileMatchupSource(); const dir = loadPlayerDirectory(); const teams = src.defenseTeams();
  const players = dir.players.filter((p) => p.gsis_id && ["QB", "RB", "WR", "TE"].includes(p.position ?? "") && p.team).slice(0, 700);
  const t0 = performance.now(); const rows: Array<{ p: (typeof players)[number]; def: string; e: MatchupEvaluation }> = [];
  for (const p of players) { const ev0 = src.resolvePlayer(p.gsis_id); if (!ev0 || !ev0.role) continue; for (const d of teams) { if (d === (ev0.team ?? "")) continue; const ctx = buildMatchupContext(src, { offense_team: ev0.team ?? "UNK", defense_team: d, week: 3 }); const e = evaluatePlayer(src, ctx, p.gsis_id); if (!("error" in e)) rows.push({ p, def: d, e }); } }
  const ms = performance.now() - t0; console.log(`evaluated ${rows.length} player×defense pairs (${new Set(rows.map((r) => r.p.gsis_id)).size} players × ${teams.length} defenses) in ${Math.round(ms)} ms = ${(ms / rows.length).toFixed(2)} ms/pair`);
  const cmp = (r: (typeof rows)[number]) => r.e.components; const find = (r: (typeof rows)[number], suffix: string) => cmp(r).find((c) => c.id.endsWith(suffix));
  const strongEv = (c: { evidence: string } | undefined) => c && (c.evidence === "STRONG" || c.evidence === "MODERATE");
  const show = (label: string, r?: (typeof rows)[number], suffix?: string) => { if (!r) { console.log(`\n[${label}] no real example found`); return; } const c = suffix ? find(r, suffix) : null; console.log(`\n[${label}]\n  ${r.p.name} (${r.e.offense_subject.position}, ${r.e.offense_subject.team}) vs ${r.def}: verdict ${r.e.structural_verdict}, generic defense pct ${r.e.generic_defense_context.overall_percentile} → ${r.e.player_specific_vs_generic}` + (c ? `\n  ${c.id}: ${c.direction} value=${c.value} z=${c.z} rank=${c.rank_among_defenses}/32 evidence=${c.evidence} inputs=${JSON.stringify(c.inputs).slice(0, 230)}` : "")); };
  const best = (f: (r: (typeof rows)[number]) => number | null, filter: (r: (typeof rows)[number]) => boolean) => rows.filter(filter).map((r) => ({ r, s: f(r) })).filter((x) => x.s != null).sort((a, b) => (b.s as number) - (a.s as number))[0]?.r;
  const manRate = (d: string) => Number(src.defense(d)?.tendency.recent?.["man_zone__man_rate"] ?? 0); const zoneHeavy = new Set([...teams].sort((a, b) => manRate(a) - manRate(b)).slice(0, 6)); const manHeavy = new Set([...teams].sort((a, b) => manRate(b) - manRate(a)).slice(0, 6));
  const isWR = (r: (typeof rows)[number]) => ["WR", "TE"].includes(r.e.offense_subject.position ?? "");
  show("zone-heavy defense vs zone-beating receiver (ADVANTAGE)", best((r) => find(r, "coverage.man_zone")?.z ?? null, (r) => isWR(r) && zoneHeavy.has(r.def) && find(r, "coverage.man_zone")?.direction === "ADVANTAGE" && strongEv(find(r, "coverage.man_zone")) === true), "coverage.man_zone");
  show("man-heavy defense vs receiver who beats man (ADVANTAGE)", best((r) => find(r, "coverage.man_zone")?.z ?? null, (r) => isWR(r) && manHeavy.has(r.def) && find(r, "coverage.man_zone")?.direction === "ADVANTAGE" && Number(find(r, "coverage.man_zone")?.inputs.man_edge) > 0), "coverage.man_zone");
  show("man-heavy defense vs zone-dependent receiver (DISADVANTAGE)", best((r) => -(find(r, "coverage.man_zone")?.z ?? 0), (r) => isWR(r) && manHeavy.has(r.def) && find(r, "coverage.man_zone")?.direction === "DISADVANTAGE"), "coverage.man_zone");
  show("explosive-suppressing defense vs deep-threat WR (DISADVANTAGE)", best((r) => -(find(r, "explosive.area")?.z ?? 0) * Number(find(r, "explosive.area")?.inputs.deep_share ?? 0), (r) => r.e.offense_subject.position === "WR" && find(r, "explosive.area")?.direction === "DISADVANTAGE" && Number(find(r, "explosive.area")?.inputs.deep_share ?? 0) > 0.15), "explosive.area");
  show("high-pressure defense vs pressure-sensitive QB (DISADVANTAGE)", best((r) => -(find(r, "pressure.response")?.z ?? 0), (r) => r.e.offense_subject.position === "QB" && find(r, "pressure.response")?.direction === "DISADVANTAGE"), "pressure.response");
  show("QB largely unaffected by a top-pressure defense (NEUTRAL despite extreme z)", best((r) => find(r, "pressure.response")?.z ?? null, (r) => r.e.offense_subject.position === "QB" && find(r, "pressure.response")?.direction === "NEUTRAL" && Math.abs(find(r, "pressure.response")?.z ?? 0) > 0.75), "pressure.response");
  show("strong run-D vs inside-heavy RB (DISADVANTAGE)", best((r) => -(find(r, "run.direction")?.z ?? 0), (r) => r.e.offense_subject.position === "RB" && find(r, "run.direction")?.direction === "DISADVANTAGE" && strongEv(find(r, "run.direction")) === true), "run.direction");
  show("run-D weak on the edge vs outside/edge-gap RB (ADVANTAGE via gap)", best((r) => find(r, "run.gap")?.z ?? null, (r) => r.e.offense_subject.position === "RB" && find(r, "run.gap")?.direction === "ADVANTAGE" && strongEv(find(r, "run.gap")) === true), "run.gap");
  show("RB vs heavy-box defense (box interaction)", best((r) => -(find(r, "run.box")?.z ?? 0), (r) => r.e.offense_subject.position === "RB" && find(r, "run.box")?.direction === "DISADVANTAGE"), "run.box");
  show("receiving RB vs vulnerable unit coverage", best((r) => find(r, "unit_coverage")?.z ?? null, (r) => r.e.offense_subject.position === "RB" && (r.e.components.find((c) => c.id === "rb.receiving.unit_coverage")?.evidence ?? "INSUFFICIENT") !== "INSUFFICIENT"), "unit_coverage");
  show("TE area interaction (middle/intermediate)", best((r) => find(r, "area.pass")?.z ?? null, (r) => r.e.offense_subject.position === "TE" && find(r, "area.pass")?.direction === "ADVANTAGE" && strongEv(find(r, "area.pass")) === true), "area.pass");
  show("STRONG defense overall, FAVORABLE structure for this player (DISAGREE)", best((r) => (r.e.generic_defense_context.overall_percentile ?? 0), (r) => r.e.structural_verdict === "FAVORABLE" && r.e.player_specific_vs_generic === "DISAGREE" && r.e.overall_evidence !== "INSUFFICIENT"));
  show("WEAK defense overall, UNFAVORABLE structure for this player (DISAGREE)", best((r) => 1 - (r.e.generic_defense_context.overall_percentile ?? 1), (r) => r.e.structural_verdict === "UNFAVORABLE" && r.e.player_specific_vs_generic === "DISAGREE" && r.e.overall_evidence !== "INSUFFICIENT"));
  const comparable = rows.filter((r) => r.e.player_specific_vs_generic !== "NOT_COMPARABLE"); const dis = comparable.filter((r) => r.e.player_specific_vs_generic === "DISAGREE").length;
  console.log(`\nINTERACTION ≠ RANK: of ${comparable.length} pairs where both a generic defense reading and a directional player-specific verdict exist, ${dis} (${(100 * dis / comparable.length).toFixed(1)}%) DISAGREE`);
  const cnt = (f: (r: (typeof rows)[number]) => boolean) => rows.filter(f).length; console.log(`verdicts: FAVORABLE ${cnt((r) => r.e.structural_verdict === "FAVORABLE")}, UNFAVORABLE ${cnt((r) => r.e.structural_verdict === "UNFAVORABLE")}, MIXED ${cnt((r) => r.e.structural_verdict === "MIXED")}, NEUTRAL ${cnt((r) => r.e.structural_verdict === "NEUTRAL")}, INSUFFICIENT ${cnt((r) => r.e.structural_verdict === "INSUFFICIENT_EVIDENCE")}`);
  console.log(`invariants: numeric_adjustment null in all=${rows.every((r) => r.e.numeric_adjustment === null)}, may_influence false=${rows.every((r) => r.e.may_influence_production === false)}, CB unsupported present=${rows.every((r) => r.e.unsupported.some((u) => u.id === "cornerback_assignment"))}, no component named cornerback/slot=${rows.every((r) => !r.e.components.some((c) => /cornerback|slot/i.test(c.id)))}`);
  // performance: single player, full team, multi-player, Book-Ready
  const one = rows[0]!; const t1 = performance.now(); for (let i = 0; i < 50; i++) evaluatePlayer(src, buildMatchupContext(src, { offense_team: one.e.game.offense_team, defense_team: one.def, week: 3 }), one.p.gsis_id); console.log(`\nperf: single player eval ${((performance.now() - t1) / 50).toFixed(2)} ms (warm)`);
  const team = one.e.game.offense_team; const tp = players.filter((p) => src.resolvePlayer(p.gsis_id)?.team === team).slice(0, 12); const t2 = performance.now(); const ctx = buildMatchupContext(src, { offense_team: team, defense_team: one.def, week: 3 }); for (const p of tp) evaluatePlayer(src, ctx, p.gsis_id); console.log(`perf: full-team (${tp.length} players, one defense context) ${(performance.now() - t2).toFixed(1)} ms`);
  for (const [topic, params] of [["matchup2.player.summary", { gsis_id: one.p.gsis_id, opponent: one.def }], ["matchup2.player.coverage", { gsis_id: one.p.gsis_id, opponent: one.def }], ["matchup2.defense.front", { team: one.def }]] as const) { const t3 = performance.now(); const r = await getEvidence({ topic, params: params as Record<string, string> }); console.log(`perf: Book-Ready ${topic}: ${Math.round(performance.now() - t3)} ms, ${r.blocks.length} blocks, ${(JSON.stringify(r.blocks).length / 1024).toFixed(1)} KB, validation ok=${r.validation?.ok}`); }
})();
